### PR TITLE
finished in 30 minutes exactly

### PR DESCRIPTION
**Pull request by seanwolter**
With NO Swift experience most of my time was spent googling for syntax and then trial-and-erroring my way through the playground. If I had to do this in our plaintext editor I would've taking much longer.

If someone has experience in Swift I bet they could knock this out in 15 minutes. I vaguely remember your solution used map or some Swift magic.

### CODE REVIEW

**Comment by jacobvanorder** [comment]
So, too easy?

**Comment by jacobvanorder** [comment]
My answer is more verbose because I show the steps but it's essentially the same thing.

**Comment by seanwolter** [comment]
Could we add a second step for more experienced candidates?
Sometimes I do a non-random secret santa implementation with apprentice candidates. If they get that then I ask them to randomize the output.

**Comment by jacobvanorder** [comment]
[Here's](https://github.com/jacobvanorder/SwiftChallenge/blob/master/SwiftChallengeJacobAnswer.playground/section-1.swift) what I was thinking.

I might go back, though, to think about adding some complexity or changing the challenge around. Would this be okay for your challenge tomorrow?

**Comment by seanwolter** [comment]
Should be a-ok for this week's challenge. He's an apprenticeship candidate.

**Pull request closed without merging**
